// Fills the "## Wikipedia" block of every kb note that names Wikipedia articles in its
// frontmatter (`wikipedia: "Formant"` or `wikipedia: ["Formant", "Vocal tract"]`) with the
// English summary and the interlanguage links Wikipedia holds for that article.
//   node scripts/kb-wiki.mjs            # update blocks in place
//   node scripts/kb-wiki.mjs --check    # only report titles that do not resolve
import fs from 'node:fs';
import path from 'node:path';

const root = 'kb';
const dirs = ['concepts', 'tutorials', '.'];
const shown = ['ja', 'zh', 'ko', 'es', 'de', 'fr', 'pt', 'it', 'ru', 'nl', 'sv', 'pl', 'tr', 'th', 'vi', 'id', 'ar', 'hi', 'uk', 'fi'];
const check = process.argv.includes('--check');
const ua = 'koenami-kb/1.0 (https://koe.transnavi.jp; knowledge-base link check)';
const get = async (url) => { const r = await fetch(url, { headers: { 'User-Agent': ua, Accept: 'application/json' } }); if (!r.ok) throw new Error(`${r.status} ${url}`); return r.json(); };

async function lookup(title) {
  const summary = await get(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title.replace(/ /g, '_'))}`);
  if (summary.type === 'disambiguation') throw new Error(`disambiguation page: ${title}`);
  const q = await get(`https://en.wikipedia.org/w/api.php?action=query&prop=langlinks&titles=${encodeURIComponent(summary.title)}&lllimit=500&format=json&redirects=1&formatversion=2`);
  const page = q.query.pages[0];
  const links = new Map((page.langlinks || []).map((l) => [l.lang, l.title]));
  return { title: summary.title, url: summary.content_urls.desktop.page, extract: summary.extract.split(/(?<=[.。])\s/)[0], links, total: links.size };
}

const wikiUrl = (lang, title) => `https://${lang}.wikipedia.org/wiki/${title.replace(/ /g, '_').replace(/\(/g, '%28').replace(/\)/g, '%29')}`;
const render = (entries) => {
  const lines = ['<!-- wiki:start — generated by scripts/kb-wiki.mjs from the frontmatter `wikipedia:` field; edit that field, not this block -->', '## Wikipedia'];
  for (const e of entries) {
    lines.push(`- **en**: [${e.title}](${e.url}) — ${e.extract}`);
    const row = shown.filter((l) => e.links.has(l)).map((l) => `${l}: [${e.links.get(l)}](${wikiUrl(l, e.links.get(l))})`);
    const rest = e.total - row.length;
    lines.push(`  ${row.join(' · ')}${rest > 0 ? ` · +${rest} more languages` : ''}`);
  }
  lines.push('<!-- wiki:end -->');
  return lines.join('\n');
};

let failures = 0, updated = 0;
for (const dir of dirs) {
  const full = path.join(root, dir);
  if (!fs.existsSync(full)) continue;
  for (const file of fs.readdirSync(full)) {
    if (!file.endsWith('.md')) continue;
    const p = path.join(full, file);
    const text = fs.readFileSync(p, 'utf8');
    const fm = text.match(/^---\n([\s\S]*?)\n---/);
    const m = fm && fm[1].match(/^wikipedia: (.*)$/m);
    if (!m) continue;
    const titles = m[1].trim().startsWith('[') ? m[1].trim().slice(1, -1).split(/,\s*/).map((t) => t.trim().replace(/^"|"$/g, '')) : [m[1].trim().replace(/^"|"$/g, '')];
    const entries = [];
    for (const t of titles) {
      try { entries.push(await lookup(t)); } catch (e) { failures++; console.log(`${dir}/${file}: ${e.message}`); }
    }
    if (check || !entries.length) continue;
    const block = render(entries);
    const next = /<!-- wiki:start[\s\S]*?<!-- wiki:end -->/.test(text) ? text.replace(/<!-- wiki:start[\s\S]*?<!-- wiki:end -->/, block) : text.replace(/\n## Related\n/, `\n${block}\n\n## Related\n`);
    if (!next.includes('wiki:start')) { console.log(`${dir}/${file}: no "## Related" section to insert before`); failures++; continue; }
    if (next !== text) { fs.writeFileSync(p, next); updated++; }
  }
}
console.log(`${updated} notes updated, ${failures} problems`);
if (failures) process.exitCode = 1;
