import {finite,clamp} from './math.js';
const PITCH_LO=65.41,PITCH_HI=523.25,NOTE_NAMES=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
export class SignalView{
 constructor(canvas,onRange,onSeek){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.onRange=onRange;this.onSeek=onSeek;this.timelineHeight=36;this.gutter=38;this.pitchUnit='note';try{if(localStorage.getItem('voice-pitch-unit')==='hz')this.pitchUnit='hz';}catch{}this.source='own';this.mode='pitch';this.overlay=true;this.dirty=true;this.images=new WeakMap();this.ranges={own:null,ref:null};this.data={own:null,ref:null};this.focus={own:null,ref:null};
  new ResizeObserver(()=>this.dirty=true).observe(canvas);new MutationObserver(()=>{this.dirty=true;this.images=new WeakMap();}).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
  canvas.addEventListener('pointerdown',e=>{if(this.mode==='pitch'&&e.offsetX<this.gutter&&e.offsetY>this.timelineHeight){this.pitchUnit=this.pitchUnit==='hz'?'note':'hz';try{localStorage.setItem('voice-pitch-unit',this.pitchUnit);}catch{}this.dirty=true;return;}if(!this.data[this.source])return;canvas.setPointerCapture(e.pointerId);this.drag={x:e.offsetX,y:e.offsetY};});
  canvas.addEventListener('pointermove',e=>{canvas.style.cursor=e.offsetY<this.timelineHeight?'ew-resize':this.mode==='pitch'&&e.offsetX<this.gutter?'pointer':'crosshair';if(this.drag){this.drag.end=e.offsetX;this.dirty=true;}});
  canvas.addEventListener('pointerup',e=>{if(!this.drag)return;const d=this.drag;this.drag=null;if(Math.abs(e.offsetX-d.x)>4){let a=this.timeAt(Math.min(d.x,e.offsetX),d.y<this.timelineHeight),b=this.timeAt(Math.max(d.x,e.offsetX),d.y<this.timelineHeight);if(b-a>=.25)this.onRange(this.source,[a,b]);}else{this.onSeek(this.source,this.timeAt(e.offsetX,d.y<this.timelineHeight));}this.dirty=true;});canvas.addEventListener('pointercancel',()=>{this.drag=null;this.dirty=true;});
  canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const duration=this.data[this.source]?.duration||0,delta=e.key==='ArrowRight'?.1:-.1;if(e.shiftKey){const r=this.ranges[this.source]||[0,Math.min(1,duration)];this.onRange(this.source,[r[0],clamp(r[1]+delta,r[0]+.25,duration)]);}else this.onSeek(this.source,clamp((this.time?.[this.source]||0)+delta,0,duration));});
 }
 pitchY(hz,top,ph){return top+(1-Math.log2(hz/PITCH_LO)/Math.log2(PITCH_HI/PITCH_LO))*ph;}
 pitchTicks(top,ph){const semis=12*Math.log2(PITCH_HI/PITCH_LO),step=[1,2,3,4,6,12].find(n=>n*ph/semis>=14)||12,ticks=[];for(let m=36;m<=72;m+=step){const hz=440*Math.pow(2,(m-69)/12);ticks.push({hz,y:this.pitchY(hz,top,ph),label:this.pitchUnit==='note'?NOTE_NAMES[m%12]+(Math.floor(m/12)-1):`${Math.round(hz)} Hz`});}return ticks;}
 timeAt(x,full=false){const duration=this.data[this.source]?.duration||0,range=full?[0,duration]:this.ranges[this.source]||[0,duration];return range[0]+clamp((x-this.gutter)/(this.width-this.gutter-10),0,1)*(range[1]-range[0]);}
 set(side,detail){this.data[side]=detail;this.focus[side]=null;this.ranges[side]=null;this.dirty=true;}
 setRange(side,range,focus=null){this.ranges[side]=range;this.focus[side]=focus;this.dirty=true;}
 image(detail,side){const spec=detail?.visuals?.spectrogram;if(!spec)return null;let cached=this.images.get(spec);if(cached?.[side])return cached[side];const bytes=Uint8Array.from(atob(spec.data),c=>c.charCodeAt(0)),canvas=document.createElement('canvas');canvas.width=spec.frames;canvas.height=spec.bins;const c=canvas.getContext('2d'),im=c.createImageData(canvas.width,canvas.height),rgb=getComputedStyle(document.documentElement).getPropertyValue(side==='own'?'--self':'--reference').trim().match(/[a-f\d]{2}/gi)?.map(v=>parseInt(v,16))||[127,123,229];for(let t=0;t<spec.frames;t++)for(let f=0;f<spec.bins;f++){const k=((spec.bins-1-f)*spec.frames+t)*4,v=bytes[t*spec.bins+f]/255;im.data[k]=rgb[0];im.data[k+1]=rgb[1];im.data[k+2]=rgb[2];im.data[k+3]=Math.round(Math.pow(v,1.75)*255);}c.putImageData(im,0,0);cached={...cached,[side]:canvas};this.images.set(spec,cached);return canvas;}
 draw(time={}){this.time=time;if(!this.dirty&&!time.animate)return;this.dirty=false;const canvas=this.canvas,c=this.ctx,w=canvas.clientWidth,h=canvas.clientHeight;this.width=w;this.height=h;const dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);if(w<30||h<20)return;const css=getComputedStyle(document.documentElement),muted=css.getPropertyValue('--muted'),grid=css.getPropertyValue('--grid'),colors={own:css.getPropertyValue('--self'),ref:css.getPropertyValue('--reference')};c.font='9px "Segoe UI",sans-serif';c.fillStyle=muted;const top=this.timelineHeight+2,ph=h-top-17,pitchTicks=this.mode==='pitch'&&ph>5?this.pitchTicks(top,ph):[];this.gutter=Math.max(38,...pitchTicks.map(t=>Math.ceil(c.measureText(t.label).width)+8));const x=this.gutter,pw=w-x-10;
  const base=this.data[this.source],dur=base?.duration||1,range=this.ranges[this.source]||[0,dur];c.strokeStyle=colors[this.source];c.lineWidth=.8;const waveform=base?.visuals?.waveform||[];c.beginPath();for(let i=0;i<waveform.length;i++){const xx=x+i/waveform.length*pw;c.moveTo(xx,18-waveform[i][1]*16);c.lineTo(xx,18-waveform[i][0]*16);}c.stroke();c.fillStyle=muted;c.fillText(this.source==='own'?'自分':'見本',2,21);
  const selection=this.drag&&finite(this.drag.end)?[this.timeAt(this.drag.x,this.drag.y<this.timelineHeight),this.timeAt(this.drag.end,this.drag.y<this.timelineHeight)]:this.ranges[this.source];if(selection){const [a,b]=selection;c.fillStyle=colors[this.source];c.globalAlpha=.18;c.fillRect(x+a/dur*pw,0,(b-a)/dur*pw,this.timelineHeight);c.globalAlpha=1;c.strokeStyle=colors[this.source];c.strokeRect(x+Math.min(a,b)/dur*pw,.5,Math.abs(b-a)/dur*pw,this.timelineHeight-1);}
  c.strokeStyle=grid;c.beginPath();c.moveTo(x,this.timelineHeight);c.lineTo(w-10,this.timelineHeight);c.stroke();
  if(base&&finite(time[this.source])&&!this.live){const progress=clamp(time[this.source]/dur,0,1),head=x+progress*pw;c.fillStyle=colors[this.source];c.globalAlpha=.08;c.fillRect(x,0,progress*pw,this.timelineHeight);c.globalAlpha=1;c.strokeStyle=colors[this.source];c.lineWidth=1.6;c.beginPath();c.moveTo(head,0);c.lineTo(head,this.timelineHeight);c.stroke();c.beginPath();c.moveTo(head-4,0);c.lineTo(head+4,0);c.lineTo(head,5);c.closePath();c.fill();}
  const sides=this.overlay?['own','ref']:[this.source];
  if(pitchTicks.length){c.strokeStyle=grid;c.lineWidth=.5;c.beginPath();for(const t of pitchTicks){c.moveTo(x,Math.round(t.y)+.5);c.lineTo(x+pw,Math.round(t.y)+.5);}c.stroke();}
  if(ph>5)for(const side of sides){const original=this.data[side],detail=this.focus[side]||original;if(!detail)continue;const active=this.ranges[side]||[0,original.duration],color=colors[side];
   if(this.mode==='pitch'){const rows=original.track||[],r=this.live&&side==='own'?[Math.max(0,original.duration-12),original.duration]:active;const yy=v=>this.pitchY(v,top,ph);if(this.pitchBand?.every(finite)&&side===sides[0]){c.fillStyle=colors.ref;c.globalAlpha=.09;c.fillRect(x,yy(this.pitchBand[1]),pw,yy(this.pitchBand[0])-yy(this.pitchBand[1]));c.globalAlpha=1;}c.beginPath();let last=null;for(const p of rows){if(p.t<r[0]||p.t>r[1])continue;if(!finite(p.f0)){last=null;continue;}const xx=x+(p.t-r[0])/(r[1]-r[0])*pw,y=yy(p.f0);if(last&&p.t-last.t<.16)c.lineTo(xx,y);else c.moveTo(xx,y);last=p;}c.strokeStyle=color;c.lineWidth=1.4;c.stroke();}
   else if(this.mode==='spectrogram'){const im=this.image(detail,side);if(im){const offset=detail.offset||0,a=clamp((active[0]-offset)/detail.duration,0,1),b=clamp((active[1]-offset)/detail.duration,0,1);c.globalAlpha=this.overlay?.78:1;c.drawImage(im,a*im.width,0,Math.max(1,(b-a)*im.width),im.height,x,top,pw,ph);c.globalAlpha=1;}}
   else if(this.mode==='spectrum'){const sp=detail.visuals?.spectrum;if(sp){c.beginPath();sp.db.forEach((v,i)=>{const xx=x+i*sp.hz_step/5000*pw,yy=top+(1-clamp((v+80)/80,0,1))*ph;if(i===0)c.moveTo(xx,yy);else c.lineTo(xx,yy);});c.strokeStyle=color;c.lineWidth=1.3;c.stroke();}}
   else{const wave=original.visuals?.waveform||[],a=Math.floor(active[0]/original.duration*wave.length),b=Math.ceil(active[1]/original.duration*wave.length);c.beginPath();for(let i=a;i<b;i++){if(!wave[i])continue;const xx=x+(i-a)/(b-a)*pw;c.moveTo(xx,top+ph/2-wave[i][1]*ph/2);c.lineTo(xx,top+ph/2-wave[i][0]*ph/2);}c.strokeStyle=color;c.globalAlpha=.65;c.stroke();c.globalAlpha=1;}
  }
  c.fillStyle=muted;c.textAlign='right';if(this.mode==='pitch'){for(const t of pitchTicks)c.fillText(t.label,x-4,clamp(t.y+3,top+7,top+ph));}else if(this.mode==='spectrogram'){c.fillText('5k',32,top+7);c.fillText('0 Hz',32,top+ph);}else if(this.mode==='spectrum'){c.fillText('0',32,top+7);c.fillText('−80 dB',34,top+ph);}c.textAlign='left';
  for(let i=0;i<=4;i++){c.textAlign=i===0?'left':i===4?'right':'center';c.fillText(this.mode==='spectrum'?`${i*1.25}k`:this.overlay?`${i*25}%`:`${(range[0]+(range[1]-range[0])*i/4).toFixed(1)}s`,x+pw*i/4,h-3);}c.textAlign='left';
  for(const side of sides){const t=time[side],orig=this.data[side];if(!finite(t)||!orig)continue;const r=this.ranges[side]||[0,orig.duration],pos=(t-r[0])/(r[1]-r[0]);if(pos<0||pos>1)continue;c.strokeStyle=colors[side];c.lineWidth=1;c.beginPath();c.moveTo(x+pos*pw,top);c.lineTo(x+pos*pw,top+ph);c.stroke();}
 }
}
window.SignalView=SignalView;
